# Generated by Django 5.2.8 on 2025-12-30 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultation_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationproject',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultationproject',
            name='taaskr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taaskr_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
