# Generated by Django 5.2.8 on 2025-12-31 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_app', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmentlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='taaskr',
        ),
        migrations.AddField(
            model_name='assignmentlog',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='assignmentlog',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignmentlog',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='bookings_app.booking'),
        ),
        migrations.AlterField(
            model_name='assignmentlog',
            name='method',
            field=models.CharField(choices=[('manual', 'Manual'), ('broadcast', 'Broadcast'), ('auto', 'Auto')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='assignmentlog',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='requested', max_length=30),
        ),
        migrations.AlterField(
            model_name='assignmentlog',
            name='taaskr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentlog',
            unique_together={('booking', 'taaskr')},
        ),
        migrations.AddIndex(
            model_name='assignmentlog',
            index=models.Index(fields=['booking', 'taaskr'], name='bookings_ap_booking_ed41a5_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentlog',
            index=models.Index(fields=['status'], name='bookings_ap_status_97da3c_idx'),
        ),
    ]
