# Generated by Django 5.2.8 on 2025-12-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_app', '0003_alter_assignmentlog_options_remove_booking_taaskr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='required_taaskrs',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
