# Generated by Django 5.2.8 on 2026-01-17 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_app', '0005_customservice_booking_custom_service_quoterequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='quotes/images/')),
                ('uploaded_by', models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('taaskr', 'Taaskr')], default='customer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bookings_app.quoterequest')),
            ],
        ),
    ]
