# Generated by Django 5.2.8 on 2026-01-17 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_app', '0006_quoteimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoterequest',
            name='address',
        ),
    ]
