# Generated by Django 5.2.8 on 2026-01-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_app', '0007_remove_quoterequest_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customservice',
            name='whats_included',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
