# Generated by Django 5.2.8 on 2026-01-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_app', '0008_customservice_whats_included'),
    ]

    operations = [
        migrations.AddField(
            model_name='customservice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
