# Generated by Django 5.2.8 on 2026-01-17 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_app', '0009_customservice_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customservice',
            name='whats_included',
        ),
    ]
