# Generated by Django 5.2.8 on 2026-01-17 12:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_app', '0010_remove_customservice_whats_included'),
    ]

    operations = [
        migrations.AddField(
            model_name='customservice',
            name='whats_included',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
    ]
