# Generated by Django 5.2.8 on 2026-01-20 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_app', '0011_customservice_whats_included'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoterequest',
            name='custom_service',
        ),
        migrations.AddField(
            model_name='customservice',
            name='quote_request',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='custom_service', to='bookings_app.quoterequest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customservice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Customer'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
