# Generated by Django 5.2.8 on 2026-02-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_app', '0013_booking_paid_amount_booking_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cod_pending', 'COD Pending'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=30),
        ),
    ]
