# Generated by Codex on 2026-03-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings_app", "0015_alter_booking_assignment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="start_otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="completion_otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="completion_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="BookingMedia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("stage", models.CharField(choices=[("before", "Before"), ("after", "After")], max_length=10)),
                ("media_type", models.CharField(choices=[("photo", "Photo"), ("audio", "Audio")], max_length=10)),
                ("file", models.FileField(upload_to="bookings/media/%Y/%m/%d/")),
                ("uploaded_by", models.CharField(choices=[("taaskr", "Taaskr"), ("customer", "Customer")], default="taaskr", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("booking", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="media", to="bookings_app.booking")),
            ],
        ),
    ]
