# Generated by Django 5.2.8 on 2025-12-30 11:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField(help_text='Start time of availability (e.g., 09:00:00)')),
                ('end_time', models.TimeField(help_text='End time of availability (e.g., 17:00:00)')),
                ('is_available', models.BooleanField(default=True, help_text='Uncheck to mark as unavailable (e.g., vacation)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Availabilities',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TaaskrProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('skill_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('certification', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=list, size=None)),
                ('rating_avg', models.FloatField(default=0.0)),
                ('total_jobs', models.PositiveIntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
