# Generated by Django 5.2.8 on 2026-01-08 12:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taaskr_app', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('taaskr', 'is_available')},
        ),
        migrations.RemoveField(
            model_name='availability',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='start_time',
        ),
    ]
