# Generated by Django 5.2.8 on 2026-03-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taaskr_app', '0004_service_area_and_profile_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicearea',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
