# Generated by Django 5.2.8 on 2026-03-25 12:17

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taaskr_app', '0005_alter_servicearea_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    """
                    DO $$
                    BEGIN
                        IF EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_name = 'taaskr_app_taaskrprofile'
                              AND column_name = 'id_proof_image'
                        ) THEN
                            ALTER TABLE taaskr_app_taaskrprofile
                            RENAME COLUMN id_proof_image TO government_id_image;
                        END IF;
                    END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                )
            ],
            state_operations=[
                migrations.RenameField(
                    model_name='taaskrprofile',
                    old_name='id_proof_image',
                    new_name='government_id_image',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    """
                    DO $$
                    BEGIN
                        IF EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_name = 'taaskr_app_taaskrprofile'
                              AND column_name = 'bank_account_name'
                        ) THEN
                            ALTER TABLE taaskr_app_taaskrprofile
                            DROP COLUMN bank_account_name;
                        END IF;
                    END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    """
                    DO $$
                    BEGIN
                        IF EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_name = 'taaskr_app_taaskrprofile'
                              AND column_name = 'bank_ifsc'
                        ) THEN
                            ALTER TABLE taaskr_app_taaskrprofile
                            DROP COLUMN bank_ifsc;
                        END IF;
                    END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    """
                    DO $$
                    BEGIN
                        IF EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_name = 'taaskr_app_taaskrprofile'
                              AND column_name = 'bank_upi'
                        ) THEN
                            ALTER TABLE taaskr_app_taaskrprofile
                            DROP COLUMN bank_upi;
                        END IF;
                    END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    """
                    DO $$
                    BEGIN
                        IF EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_name = 'taaskr_app_taaskrprofile'
                              AND column_name = 'service_areas'
                        ) THEN
                            ALTER TABLE taaskr_app_taaskrprofile
                            DROP COLUMN service_areas;
                        END IF;
                    END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='taaskrprofile',
                    name='bank_account_name',
                ),
                migrations.RemoveField(
                    model_name='taaskrprofile',
                    name='bank_ifsc',
                ),
                migrations.RemoveField(
                    model_name='taaskrprofile',
                    name='bank_upi',
                ),
                migrations.RemoveField(
                    model_name='taaskrprofile',
                    name='service_areas',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    """
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_name = 'taaskr_app_servicearea'
                              AND column_name = 'created_at'
                        ) THEN
                            ALTER TABLE taaskr_app_servicearea
                            ADD COLUMN created_at timestamp with time zone NULL;
                            UPDATE taaskr_app_servicearea
                            SET created_at = NOW()
                            WHERE created_at IS NULL;
                            ALTER TABLE taaskr_app_servicearea
                            ALTER COLUMN created_at SET NOT NULL;
                        END IF;
                    END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    """
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_name = 'taaskr_app_servicearea'
                              AND column_name = 'state'
                        ) THEN
                            ALTER TABLE taaskr_app_servicearea
                            ADD COLUMN state varchar(100);
                        END IF;
                    END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    """
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_name = 'taaskr_app_servicearea'
                              AND column_name = 'updated_at'
                        ) THEN
                            ALTER TABLE taaskr_app_servicearea
                            ADD COLUMN updated_at timestamp with time zone NULL;
                            UPDATE taaskr_app_servicearea
                            SET updated_at = NOW()
                            WHERE updated_at IS NULL;
                        END IF;
                    END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='servicearea',
                    name='created_at',
                    field=models.DateTimeField(
                        auto_now_add=True, default=django.utils.timezone.now),
                    preserve_default=False,
                ),
                migrations.AddField(
                    model_name='servicearea',
                    name='state',
                    field=models.CharField(
                        default=django.utils.timezone.now, max_length=100),
                    preserve_default=False,
                ),
                migrations.AddField(
                    model_name='servicearea',
                    name='updated_at',
                    field=models.DateTimeField(auto_now=True),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    """
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_name = 'taaskr_app_taaskrprofile'
                              AND column_name = 'bank_account_holder_name'
                        ) THEN
                            ALTER TABLE taaskr_app_taaskrprofile
                            ADD COLUMN bank_account_holder_name varchar(150) NULL;
                        END IF;
                    END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    """
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_name = 'taaskr_app_taaskrprofile'
                              AND column_name = 'bank_ifsc_code'
                        ) THEN
                            ALTER TABLE taaskr_app_taaskrprofile
                            ADD COLUMN bank_ifsc_code varchar(32) NULL;
                        END IF;
                    END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    """
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_name = 'taaskr_app_taaskrprofile'
                              AND column_name = 'bank_upi_id'
                        ) THEN
                            ALTER TABLE taaskr_app_taaskrprofile
                            ADD COLUMN bank_upi_id varchar(150) NULL;
                        END IF;
                    END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    """
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_name = 'taaskr_app_taaskrprofile'
                              AND column_name = 'bank_verified'
                        ) THEN
                            ALTER TABLE taaskr_app_taaskrprofile
                            ADD COLUMN bank_verified boolean NOT NULL DEFAULT false;
                        END IF;
                    END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    """
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_name = 'taaskr_app_taaskrprofile'
                              AND column_name = 'documents_verified'
                        ) THEN
                            ALTER TABLE taaskr_app_taaskrprofile
                            ADD COLUMN documents_verified boolean NOT NULL DEFAULT false;
                        END IF;
                    END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    """
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_name = 'taaskr_app_taaskrprofile'
                              AND column_name = 'onboarding_completed'
                        ) THEN
                            ALTER TABLE taaskr_app_taaskrprofile
                            ADD COLUMN onboarding_completed boolean NOT NULL DEFAULT false;
                        END IF;
                    END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    """
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_name = 'taaskr_app_taaskrprofile'
                              AND column_name = 'verification_note'
                        ) THEN
                            ALTER TABLE taaskr_app_taaskrprofile
                            ADD COLUMN verification_note text NULL;
                        END IF;
                    END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    """
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_name = 'taaskr_app_taaskrprofile'
                              AND column_name = 'verification_status'
                        ) THEN
                            ALTER TABLE taaskr_app_taaskrprofile
                            ADD COLUMN verification_status varchar(20) NOT NULL DEFAULT 'pending';
                        END IF;
                    END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='taaskrprofile',
                    name='bank_account_holder_name',
                    field=models.CharField(
                        blank=True, max_length=150, null=True),
                ),
                migrations.AddField(
                    model_name='taaskrprofile',
                    name='bank_ifsc_code',
                    field=models.CharField(
                        blank=True, max_length=32, null=True),
                ),
                migrations.AddField(
                    model_name='taaskrprofile',
                    name='bank_upi_id',
                    field=models.CharField(
                        blank=True, max_length=150, null=True),
                ),
                migrations.AddField(
                    model_name='taaskrprofile',
                    name='bank_verified',
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name='taaskrprofile',
                    name='documents_verified',
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name='taaskrprofile',
                    name='onboarding_completed',
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name='taaskrprofile',
                    name='verification_note',
                    field=models.TextField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='taaskrprofile',
                    name='verification_status',
                    field=models.CharField(default='pending', max_length=20),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='radius_km',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='taaskrprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='taaskrprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='taaskrprofile',
            name='certification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taaskrprofile',
            name='skill_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(
                max_length=100), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='taaskrprofile',
            name='total_jobs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='servicearea',
            table='taaskr_app_servicearea',
        ),
    ]
