# Generated by Django 5.2.8 on 2026-03-25 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taaskr_app', '0006_rename_id_proof_image_taaskrprofile_government_id_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    """
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM information_schema.tables
                            WHERE table_name = 'taaskr_app_taaskrservicearea'
                        ) THEN
                            CREATE TABLE taaskr_app_taaskrservicearea (
                                id BIGSERIAL PRIMARY KEY,
                                created_at TIMESTAMPTZ NOT NULL,
                                service_area_id BIGINT NOT NULL,
                                taaskr_id BIGINT NOT NULL,
                                CONSTRAINT taaskr_app_taaskrservicearea_service_area_id_fk
                                    FOREIGN KEY (service_area_id)
                                    REFERENCES taaskr_app_servicearea(id)
                                    DEFERRABLE INITIALLY DEFERRED,
                                CONSTRAINT taaskr_app_taaskrservicearea_taaskr_id_fk
                                    FOREIGN KEY (taaskr_id)
                                    REFERENCES users_app_user(id)
                                    DEFERRABLE INITIALLY DEFERRED
                            );

                            CREATE UNIQUE INDEX IF NOT EXISTS taaskr_app_taaskrservicearea_taaskr_id_service_area_id_uniq
                                ON taaskr_app_taaskrservicearea (taaskr_id, service_area_id);
                        END IF;
                    END $$;
                    """,
                    reverse_sql="",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='TaaskrServiceArea',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('service_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taaskr_links', to='taaskr_app.servicearea')),
                        ('taaskr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taaskr_service_areas', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'taaskr_app_taaskrservicearea',
                        'unique_together': {('taaskr', 'service_area')},
                    },
                ),
            ],
        ),
    ]
