# Generated by Django 5.2.8 on 2026-03-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='whats_included',
            field=models.TextField(blank=True, default=''),
        ),
    ]
