# Generated by Django 5.2.8 on 2026-01-30 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_app', '0013_booking_paid_amount_booking_payment_status_and_more'),
        ('payments_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='created_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.CharField(default='razorpay', max_length=30),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings_app.booking'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('cod', 'Cash on Delivery'), ('upi', 'UPI'), ('wallet', 'Wallet'), ('admin_adjustment', 'Admin Adjustment')], max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('failed', 'Failed'), ('pending', 'Pending'), ('refunded', 'Refunded')], default='initiated', max_length=30),
        ),
    ]
