# Generated by Django 5.2.8 on 2026-01-31 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_app', '0002_payment_created_by_admin_payment_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField(blank=True)),
                ('refund_mode', models.CharField(choices=[('razorpay', 'Razorpay'), ('cash', 'Cash'), ('adjustment', 'Adjustment')], default='razorpay', max_length=30)),
                ('refund_status', models.CharField(choices=[('initiated', 'Initiated'), ('processed', 'Processed'), ('failed', 'Failed')], default='initiated', max_length=30)),
                ('provider_refund_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments_app.payment')),
            ],
        ),
    ]
